paths:
  jquery: 'jquery-1.10.1'
  underscore: 'lodash.underscore-1.2.1'
  backbone: 'backbone-1.0.0'
  chaplin: 'chaplin-0.9.0'
  raphael: 'raphael-2.1.0'
  eve: 'eve-0.3.4'
  configuration: 'empty:'
  translations: 'lib/translations'
shim:
  raphael:
    deps: ['eve']
    exports: 'Raphael'
  'jquery.sortable':
    deps: ['jquery']
    exports: 'jQuery.fn.sortable'
  underscore:
    exports: '_'
  backbone:
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
